namespace Linq2Azure.VirtualMachines
{
    public interface IRoleOSVirtualHardDisk
    {
        ISpecifyMediaForOS WithDiskName(string name);
        ISpecifyMediaForOS WithAutoGeneratedDiskName();
    }
}